### ISSUE TITLE
Linux dependencies (Ubuntu)

### ISSUE THREAD

**Issue by DuaneNielsen** [YilingQiao/diffsim#3]
Few dependencies not mentioned in the docs.

sudo apt install gcc-4.8 gcc-5
sudo apt-get install libblas-dev liblapack-dev
sudo apt-get install libopenblas-dev
sudo apt-get install gfortran
sudo apt-install scons
sudo apt-install libpng-dev

**Comment by DuaneNielsen** [comment]
One I'm struggling to figure out is this dependency from the setup

```
/home/duane/miniconda3/envs/diffsim/compiler_compat/ld: cannot find -lmake_pytorch
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```

**Comment by YilingQiao** [comment]
Thanks! I've updated the readme file.

**Comment by DuaneNielsen** [comment]
Cheers.  We read your paper yesterday in our meetup group.

Really cool work, can't wait to play around with it!
