### ISSUE TITLE
isnan and isinf declared twice

### ISSUE THREAD

**Issue by DuaneNielsen** [YilingQiao/diffsim#4]
On my system, it appears the arcsim/dependencies/include/taucs.h suffers from a problem where isinf and isnan are already declared, but as functions, in a the included math library, and the #ifndef guards do not function, as they expect a macro, not a function.

I hacked a fix by commenting out these lines, and the code seems to compile and run.

arcsim/dependencies/include/taucs.h:804

I replaced..

```
#ifndef isnan
extern int isnan(double);
#endif
#ifndef finite
extern int finite(double);
#endif
#ifndef isinf
extern int isinf(double);
#endif

```

with

```
/* #ifndef isnan
extern int isnan(double);
#endif
*/
#ifndef finite
extern int finite(double);
#endif
/*
#ifndef isinf
extern int isinf(double);
#endif
*/

```

**Comment by YilingQiao** [comment]
Thanks, I think you are right. This safeguard may be too old and I also comment them out.

**Comment by DuaneNielsen** [comment]
I'll rebuild this afternoon and let you know.

**Comment by DuaneNielsen** [comment]
Compiles ok for me now.  By the way... the build script didn't work for me.. this is how I ended up compiling.

```
conda install pip
pip install -r requirements.txt
cd arcsim/dependencies/taucs/
chmod 755 ./configure
./configure
make
cd ..
make
cd ../..
make -j 8
python setup.py install
```
