### ISSUE TITLE
Collision Resolution Unable to Converge

### ISSUE THREAD

**Issue by Ericcsr** [YilingQiao/diffsim#5]
Hi, when using the diffsim framework, it is very likely that during the training process, the code will yield Collision Resolution Unable to Converge problem from `arcsim.step()` even when the max iteration has been changed to 10,000. May I know what scenario will lead to such a problem?

**Comment by YilingQiao** [comment]
What kind of scene are you using? Is it possible to share the config file and models with me? Does it contain too many bodies with weird shapes? Or is the time step too large?

**Comment by DuaneNielsen** [comment]
According to the paper, the collision resolution solves this minimization problem...

![image](https://user-images.githubusercontent.com/11070508/92159209-e2fedf00-ede1-11ea-919b-60afd97a5fc3.png)

You might want to dump the EE and VF values when you hit the error and figure out what geometry is that is causing the issue.  I would guess if the geometry is complex around the impact zone and the time interval is large, then the optimization problem might end up being non-convex in some cases.  For example due multiple edges/vertices of the geometry on the same object colliding in the same time slice.

**Comment by Ericcsr** [comment]
> What kind of scene are you using? Is it possible to share the config file and models with me? Does it contain too many bodies with weird shapes? Or is the time step too large?

I simply use the exp_learn_cloth example in the pysim, but I make the manipulation degree of freedom expanded to 3D, I found out when steps are more than 60 the problem is very likely to occur.
