### ISSUE TITLE
Specifying constraints on objects.

### ISSUE THREAD

**Issue by DuaneNielsen** [YilingQiao/diffsim#6]
Thanks again for the great paper and code.

I'd like to constrain movement of some of the objects so they can only move with 1 or 2 DF, so I can do some simple 2D experiments.

Is there an example of how to do that somewhere?  I was unable to find an example.

**Comment by YilingQiao** [comment]
Hi, I think you may optimize only for the DOFs you want during collision resolving, but there could be some extra work to modify the code.

Our repo focuses on the mesh-based models and the two-way coupling between cloth and rigid bodies. If you are interested in articulation, maybe you can take a look at this one
https://github.com/google-research/tiny-differentiable-simulator

**Comment by DuaneNielsen** [comment]
Yeah, I read the code over the weekend and came to the same conclusion!  Thanks for the link and also for the knowledge, appreciated!
