### ISSUE TITLE
Visualization of the Examples

### ISSUE THREAD

**Issue by gonultasbu** [YilingQiao/diffsim#9]
Hello,

I have managed to run the examples and their corresponding visualizations locally but the visualizations do not look like the ones in the repository. When I run the msim.py, the visualization appears but the meshes are all white and everything is texture-free. Do we need to make other changes to make the textures appear? I am attaching a representative screenshot to explain what I mean.

Thank you for your great contribution.
![image](https://user-images.githubusercontent.com/19195222/137535072-2d888280-30ba-483d-9c18-7772e5fb8330.png)

**Comment by YilingQiao** [comment]
Yeah, the visualization during runtime is rather simple. 

To make the demos, we take out the simulated meshes and render them in Blender.

**Comment by gonultasbu** [comment]
That makes sense. Thank you for your quick answer.
